### ISSUE TITLE
`raco fmt` adds `;` before shebang

### ISSUE THREAD

**Issue by gussmith23** [sorawee/fmt#35] opened 2022-06-29 16:05 UTC
Minimal example:

tmp.rkt:
```
#!/usr/bin/racket
```

`raco fmt tmp.rkt`:
```
;#!/usr/bin/racket
```

**Comment by sorawee** [comment] 2022-06-29 16:12
Thanks for the report, Gus! This is a duplicate of #31, which is already fixed. You can upgrade to the latest version with `raco pkg update fmt`.

**Closed by sorawee** 2022-06-29 16:12 UTC
